name: Run tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Include tags in the checkout
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Configure poetry for caching
        run: |
          # https://github.com/dschep/install-poetry-action/issues/11
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config cache-dir ~/.poetry
          poetry config virtualenvs.path ~/.poetry/virtualenv

      - name: Cache poetry virtualenv
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

    - name: Install dependencies
      working-directory: ./vcap_utils
      run: poetry install -E easy

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

    - name: Test with pytest
      run: pytest
